### ISSUE TITLE
The fan speed controlling does not work with GUNNIR A750 card

### ISSUE THREAD

**Issue by Cloudrideryx** [Rem0o/FanControl.IntelCtlLibrary#2]
![image](https://github.com/user-attachments/assets/58dd9c23-ac42-486a-8a5e-4fe791bcc278)
I tried to set the fan speed to 100%, but the control failed, fan speed is still controlled by itself. (FULL Speed is 3000 RPM)
Version 199
GPU: GUNNIR Intel Arc A750 Photon 16G OC W

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.IntelCtlLibrary/issues/1#issuecomment-2233644113

We ain't there yet. Haven't figured a way to make it work.

**Comment by Cloudrideryx** [comment]
Thank you, didn't notice this comment.
